### ISSUE TITLE
Node Module for CryptoCompare API and appending to DOM via EJS

### ISSUE THREAD

**Issue by RajisteB** [Cityslick/CryptoApp#1]
Trying to route data from API call to the DOM. My crypto-compare API comes with an npm modules, which, once installed, requires "global-fetch". I call the data but when I export it and execute npm run dev, there is an error that says Route.get() requires a callback function but got a [object Object].

I know this points to my "crypto-routes" folder which has the code:

const express = require('express');
const cryptoRouter = express.Router();
const getCrypto = require('../services/crypto/crypto-helper');
const authHelpers = require('../services/auth/auth-helpers');
// const cryptoController = require('../controllers/crypto-controller');
const liveCrypto = require('../controllers/livecrypto-controller');

cryptoRouter.get('/dashboard', getCrypto, liveCrypto);

module.exports = cryptoRouter;

...but I do not know how to fix it...

**Comment by drew-mahrt** [comment]
I'll try to take a look at this today after my meetings. Until then, try to go to the SRC and see if they can help.
