### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by jakemeltzer333** [Cityslick/CryptoApp#10]
A couple quick notes:

-You should leave more comments in your code that explains simply what some of your more complex functions do, especially your API calls. I got that your `showData` function was basically putting each of those characteristics for each cryptocurrency on the page using DOM manipulation, but the main thing for me was I wanted you to make quick comments about when you're using functions that require NPMs, such as the `getPrices` function in your cryto-helpers file to use one example.

-It didn't look like your `usersController.delete` function actually did anything, so not sure it needed to be there.

Otherwise it was really cool seeing how you got all the info to render on your pages and how much data you were able to get. I can't imagine how much work that took!

**Comment by RajisteB** [comment]
Thanks!

I definitely need to add more comments in general just to really follow what's going on a lot better. My delete function was still "under construction" in a way but I didn't get to finish it in time. Getting the API was a bit of a pain but I managed to do something similar to you but this time I put my database table name property in my api call to get the various bits that I needed.

**Comment by dominic-farquharson** [comment]
NPM Packages!
