### ISSUE TITLE
User auth login goes to database but /user page keeps redirecting to login page

### ISSUE THREAD

**Issue by RajisteB** [Cityslick/CryptoApp#2]
I must be missing something or am not looking in the right folder but everytime I login it redirected me to my index page, but now it's redirecting me back to the login page. When I take my auth.loginrequired out of the authRouter.get method, my pages work as intended. I get no errors and users are still added to database. Can't figure out what is wrong...

**Comment by drew-mahrt** [comment]
Is your latest code on github? The last commit I see is from 12 hours ago.

**Comment by RajisteB** [comment]
Yea...I committed last night and found the error this morning.
I just re-committed again with my current code.
