### ISSUE TITLE
Trying to iterate through object API data and append to the DOM via a loop

### ISSUE THREAD

**Issue by RajisteB** [Cityslick/CryptoApp#4]
dash.js script

$(function() {
    console.log('dash.js is loaded!')
});

$(document).ready(function() {
    console.log('getting prices...');
    $.ajax({
        url: 'https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,BCH,ETH,LTC,XEM,XRP,DASH,ZEC,DGB&tsyms=USD',
        success: function(data) {
                console.log(data);
                getCoinData(data);
        }
    })
    function getCoinData(data) {
        for (price in data.DISPLAY) {
            if (price === currency[0]) {
                console.log(data.DISPLAY.currency[0].USD);
            }
        }

    }
});

There are like 3 - 4 levels through which I have to go thru in order to get the data that I want>>>>
Object > DISPLAY > [SYMBOL] > USD > [DATA that I want]

I can't seem to get a loop for the symbol with an if conditional because I get an error that says it's undefined...

**Comment by drew-mahrt** [comment]
Can you give me a link to the whole file? It's hard to read the code in this format.

**Comment by RajisteB** [comment]
Sry about that.
link: https://github.com/Cityslick/CryptoApp/blob/master/public/scripts/dash.js

Edit: The price variable emits the symbol as a string but not as the next level in the entire object.

**Comment by drew-mahrt** [comment]
First, the code in your original issue doesn't match the file you sent.

In the code above, you are comparing some array currency against price. Where is that array from? I don't see it being declared anywhere.

**Comment by RajisteB** [comment]
That was a typo that I removed...I was testing to see if it worked with an array...

**Comment by drew-mahrt** [comment]
Which is the correct version of the dash.js file then? The current version never even calls getCoinData. Please update the file you linked and I'll look at that.

**Comment by RajisteB** [comment]
dash file is now correct...
link: https://github.com/Cityslick/CryptoApp/blob/master/public/scripts/dash.js

**Comment by RajisteB** [comment]
Solved issue...looked through MDN, had to put my console.log(coin) in bracket notation console.log(data.DISPLAY[coin].USD);
Now I get all the nested objects and I can append to the DOM.
Sry for the mix-up with the code, I was trying a bunch of different things...
